name: Deploy to production

on:
  push:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Install Node & dependencies
        uses: actions/setup-node@v3
        with:
          node-version: 16
      - run: npm ci

      - name: Build assets
        run: npm run build

      - name: Copy and rename htaccess
        run: npm run htaccess

      - name: Copy file via ssh password
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          password: ${{ secrets.SSH_PASSWORD }}
          port: ${{ secrets.SSH_PORT }}
          source: "dist/*"
          target: "web/genshin-carte-interactive"
          strip_components: 1
          rm: true